//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MusicSchoolContext : DbContext
    {
        public MusicSchoolContext()
            : base("name=MusicSchoolContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CanceledLesson> CanceledLessons { get; set; }
        public virtual DbSet<Lecture> Lectures { get; set; }
        public virtual DbSet<Parent> Parents { get; set; }
        public virtual DbSet<PostponedLesson> PostponedLessons { get; set; }
        public virtual DbSet<ReceivedPayment> ReceivedPayments { get; set; }
        public virtual DbSet<RoomLecture> RoomLectures { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<TeacherLecture> TeacherLectures { get; set; }
        public virtual DbSet<TeacherPayment> TeacherPayments { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<WeeklyProgram> WeeklyPrograms { get; set; }
    }
}
