//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.WeeklyPrograms = new HashSet<WeeklyProgram>();
        }
    
        public int Id { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public bool isFemale { get; set; }
        public Nullable<int> FatherId { get; set; }
        public Nullable<int> MotherId { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string School { get; set; }
        public string Job { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Reference { get; set; }
        public string UserId { get; set; }
        public bool isActive { get; set; }
    
        public virtual Parent Parent { get; set; }
        public virtual Parent Parent1 { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeeklyProgram> WeeklyPrograms { get; set; }
    }
}
