//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherPayment
    {
        public int Id { get; set; }
        public bool isActive { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string Name { get; set; }
        public int TeacherId { get; set; }
        public decimal Payment { get; set; }
    
        public virtual Teacher Teacher { get; set; }
    }
}
