//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeeklyProgram
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WeeklyProgram()
        {
            this.CanceledLessons = new HashSet<CanceledLesson>();
            this.PostponedLessons = new HashSet<PostponedLesson>();
            this.PostponedLessons1 = new HashSet<PostponedLesson>();
            this.ReceivedPayments = new HashSet<ReceivedPayment>();
        }
    
        public int Id { get; set; }
        public System.DateTime AddedDate { get; set; }
        public int TeacherId { get; set; }
        public int LectureId { get; set; }
        public int StudentId { get; set; }
        public int RoomId { get; set; }
        public int Day { get; set; }
        public int Hour { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Note { get; set; }
        public string UserId { get; set; }
        public int Type { get; set; }
        public bool isActive { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CanceledLesson> CanceledLessons { get; set; }
        public virtual Lecture Lecture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostponedLesson> PostponedLessons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostponedLesson> PostponedLessons1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceivedPayment> ReceivedPayments { get; set; }
        public virtual Room Room { get; set; }
        public virtual Student Student { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual User User { get; set; }
    }
}
